### ISSUE TITLE
Initial POC work

### ISSUE THREAD

**Issue by kerrydh** [b-rant/5Straight#23]
Initial work to test the integration of the basic AWS components that will be used by the app.

- [ ] Define the API Gateway
- [ ] Configure a DynamoDB
- [ ] Create OnConnect Lambda
- [ ] Create OnDisconnect Lambda
- [ ] Create ConnectionCount Lambda
- [ ] Configure S3 bucket to host website
- [ ] Write Blazer web assembly
